language: node_js
node_js:
  - 14

before_install: npm run dist

deploy:
  skip_cleanup: true
  provider: script

  script: npm run release
  on:
    tags: true

env:
  EXTENSION_ID=dahnmmlhchpmmlgebpkpaofbefjdlpin
  