name: Bundle, zip and create tag on Github
on:
  push:
    branches:
      - development
jobs:
  publish:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup NodeJS 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: npm install

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: "development"

      - name: Bump version in project files
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "${{ steps.tag_version.outputs.previous_version  }}" 
          replace: "${{ steps.tag_version.outputs.new_version }}"
          exclude: "/node_modules"

      - name: Bundle with Webpack
        run: npm run build

      - name: Zip release files
        uses: papeloto/action-zip@v1
        with:
          files: dist
          recursive: true
          dest: release.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          path: dist
