name: Testing last tag acion
on:
  push:
    branches:
      - fix_build
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - uses: oprypin/find-latest-tag@v1
        id: latest_tag
        with:
          repository: gamersclub-booster/gamersclub-booster
          releases-only: false

      - run: echo "The latest tag is ${{ steps.latest_tag.outputs.tag }}"
